### ISSUE TITLE
Example syntax

### ISSUE THREAD

**Issue by CalamariAce** [cps5155/yamaha-receiver-api#7]
The readme example usage is:

`node ./lib/webServer.js -MAC=AA:BB:CC:DD:EE:FF`

In my environment, it only worked using a double-dash for "MAC" and with lower-case hex digits. Working example:

`node ./lib/webServer.js --MAC=aa:bb:cc:dd:ee:ff`

The first fix is needed for the webserver to accept the argument, and the second fix is needed for the webserver to locate the receiver.

npm version is `6.13.4`

**Comment by cps5155** [comment]
Looks like `--` is the right way to indicate a single "long-named" command line argument, however when I did this back on git bash on a Windows box that worked fine. Running currently on a MacOS the `-MAC` does not work as expected, but `--MAC` does. The capitalization of the address did not matter at the time, and I no longer have access to my old Yamaha receiver to test it out. 

I updated the readme in the linked pull request (now merged) to indicate there may be a difference in command line syntax depending on the OS this is running on. 

If you are adamant it should be changed, feel free to submit a PR.
